### ISSUE TITLE
ModalItem.vue and Modal.vue missing

### ISSUE THREAD

**Issue by crazyTweek** [JounQin/vue-async-modal#121]
Hi everybody!

I was using you library, but with the newest update (conversion to typescript) there are some errors:

After NPM install there is a lib folder under node_modules/vue-async-modal

in lib/index.js there are 2 exports:
```
export { default as Modal } from './Modal.vue';
export { default as ModalItem } from './ModalItem.vue';
```

Unfortunately the Modal.vue and ModalItem.vue are missing. 
Interestingly, they are available in the src folder in the Github repo, so I guess they are lost during compilation?

![image](https://user-images.githubusercontent.com/6828237/76773108-3765c200-67a2-11ea-94e4-f3d4c3574d0e.png)

I would add them manually, but then I can't update my node packages anymore.

Thanks for your help! :)

**Comment by JounQin** [comment]
Sorry for this issue, I'll check ASAP.

**Comment by JounQin** [comment]
@crazyTweek Please try v1.1.1

**Comment by crazyTweek** [comment]
@JounQin 
Works! 
Thank you very much for the fast fix! :)
